# Generated by Django 3.2.2 on 2021-05-28 13:39

from django.db import migrations, models
import django.db.models.deletion
import store_mgmt.utils.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company_region', models.CharField(blank=True, max_length=10, null=True)),
                ('company_town', models.CharField(blank=True, max_length=10, null=True)),
                ('company_address', models.CharField(blank=True, max_length=60, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('company_ext', models.CharField(blank=True, max_length=20, null=True)),
                ('company_contact_person', models.CharField(blank=True, max_length=30, null=True)),
                ('company_email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_contact_person', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_email', models.CharField(blank=True, max_length=100, null=True)),
                ('uniform_numbers', models.CharField(blank=True, max_length=50, null=True)),
                ('company_url', models.URLField(blank=True, null=True)),
                ('company_info', models.TextField(blank=True, null=True)),
                ('company_active', models.BooleanField(blank=True, null=True)),
                ('updated', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MgmtUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('auth', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('public_key', models.CharField(blank=True, max_length=200)),
                ('private_key', models.CharField(blank=True, max_length=200)),
                ('session_expire', models.DateTimeField()),
                ('image', models.ImageField(storage=store_mgmt.utils.storage.ImageStorage(), upload_to='./static/user_images')),
                ('action', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProductInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('types', models.CharField(blank=True, max_length=30, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('updated', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_product', to='store_mgmt.companyinfo')),
            ],
        ),
    ]
