# Generated by Django 3.2.2 on 2021-06-17 14:53

from django.db import migrations, models
import django.db.models.deletion
import store_mgmt.utils.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=10, null=True)),
                ('town', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('ext', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_contact_person', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_email', models.CharField(blank=True, max_length=100, null=True)),
                ('uniform_numbers', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('updated', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProductInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('types', models.CharField(blank=True, max_length=30, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('selling_price', models.FloatField(blank=True, null=True)),
                ('image1', models.ImageField(storage=store_mgmt.utils.storage.ImageStorage(), upload_to='./static/product_images')),
                ('image2', models.ImageField(storage=store_mgmt.utils.storage.ImageStorage(), upload_to='./static/product_images')),
                ('image3', models.ImageField(storage=store_mgmt.utils.storage.ImageStorage(), upload_to='./static/product_images')),
                ('info', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('updated', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_product', to='store_mgmt.companyinfo')),
            ],
        ),
        migrations.CreateModel(
            name='MgmtUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('auth', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('public_key', models.CharField(blank=True, max_length=200)),
                ('private_key', models.CharField(blank=True, max_length=200)),
                ('session_expire', models.DateTimeField()),
                ('image', models.ImageField(storage=store_mgmt.utils.storage.ImageStorage(), upload_to='./static/user_images')),
                ('action', models.DateTimeField()),
                ('active', models.BooleanField(blank=True, null=True)),
                ('updated', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('selling_price', models.FloatField(blank=True, null=True)),
                ('image1', models.ImageField(storage=store_mgmt.utils.storage.ImageStorage(), upload_to='./static/product_images')),
                ('image2', models.ImageField(storage=store_mgmt.utils.storage.ImageStorage(), upload_to='./static/product_images')),
                ('image3', models.ImageField(storage=store_mgmt.utils.storage.ImageStorage(), upload_to='./static/product_images')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('product_in_stock', models.FloatField(blank=True, null=True)),
                ('purchase_date', models.DateTimeField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('updated', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_mgmt.companyinfo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_mgmt.companyproductinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SellInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('selling_price', models.FloatField(blank=True, null=True)),
                ('selling_amount', models.FloatField(blank=True, null=True)),
                ('selling_remark', models.TextField(blank=True, null=True)),
                ('selling_date', models.DateTimeField()),
                ('active', models.BooleanField(blank=True, null=True)),
                ('updated', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_mgmt.companyinfo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_mgmt.companyproductinfo')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_mgmt.purchaseinfo')),
            ],
        ),
    ]
