# Generated by Django 3.2.2 on 2021-05-30 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='company_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='company_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='company_contact_person',
            new_name='contact_person',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='company_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='company_ext',
            new_name='ext',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='company_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='company_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='company_region',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='company_town',
            new_name='town',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='company_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='companyproductinfo',
            name='company_name',
        ),
    ]
