# Generated by Django 3.2.2 on 2021-06-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SellInfo',
            new_name='SaleInfo',
        ),
        migrations.RenameField(
            model_name='companyproductinfo',
            old_name='selling_price',
            new_name='sale_price',
        ),
        migrations.RenameField(
            model_name='purchaseinfo',
            old_name='selling_price',
            new_name='sale_price',
        ),
        migrations.RenameField(
            model_name='saleinfo',
            old_name='selling_amount',
            new_name='sale_amount',
        ),
        migrations.RenameField(
            model_name='saleinfo',
            old_name='selling_date',
            new_name='sale_date',
        ),
        migrations.RenameField(
            model_name='saleinfo',
            old_name='selling_price',
            new_name='sale_price',
        ),
        migrations.RenameField(
            model_name='saleinfo',
            old_name='selling_remark',
            new_name='sale_remark',
        ),
    ]
