# Generated by Django 3.2.2 on 2021-06-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcontrol',
            name='company_product_list',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
