# Generated by Django 3.2.2 on 2021-06-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_mgmt', '0002_authcontrol_company_product_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcontrol',
            name='company_main',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
