# Generated by Django 3.2.2 on 2021-06-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_mgmt', '0002_auto_20210530_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproductinfo',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyproductinfo',
            name='selling_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
