# Generated by Django 3.2.2 on 2021-06-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_mgmt', '0003_auto_20210601_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproductinfo',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
