# Generated by Django 3.2.2 on 2021-06-01 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_mgmt', '0004_companyproductinfo_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyproductinfo',
            name='company_name',
        ),
    ]
