# Generated by Django 3.2.2 on 2021-06-01 21:49

from django.db import migrations, models
import store_mgmt.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('store_mgmt', '0005_remove_companyproductinfo_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproductinfo',
            name='image1',
            field=models.ImageField(default='', storage=store_mgmt.utils.storage.ImageStorage(), upload_to='./static/product_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyproductinfo',
            name='image2',
            field=models.ImageField(default='', storage=store_mgmt.utils.storage.ImageStorage(), upload_to='./static/product_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyproductinfo',
            name='image3',
            field=models.ImageField(default=0, storage=store_mgmt.utils.storage.ImageStorage(), upload_to='./static/product_images'),
            preserve_default=False,
        ),
    ]
