# Generated by Django 3.2.2 on 2021-06-06 14:01

from django.db import migrations, models
import django.db.models.deletion
import store_mgmt.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('store_mgmt', '0006_auto_20210601_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('selling_price', models.FloatField(blank=True, null=True)),
                ('image1', models.ImageField(storage=store_mgmt.utils.storage.ImageStorage(), upload_to='./static/product_images')),
                ('image2', models.ImageField(storage=store_mgmt.utils.storage.ImageStorage(), upload_to='./static/product_images')),
                ('image3', models.ImageField(storage=store_mgmt.utils.storage.ImageStorage(), upload_to='./static/product_images')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('product_in_stock', models.FloatField(blank=True, null=True)),
                ('purchase_date', models.DateTimeField()),
                ('info', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('updated', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_mgmt.companyinfo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_mgmt.companyproductinfo')),
            ],
        ),
    ]
