# Generated by Django 3.2.2 on 2021-06-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_mgmt', '0007_purchaseinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgmtuser',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
