# Generated by Django 3.2.2 on 2021-06-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_mgmt', '0008_mgmtuser_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinfo',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
