# Generated by Django 3.2.2 on 2021-06-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_mgmt', '0009_purchaseinfo_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinfo',
            name='info',
        ),
    ]
