# Generated by Django 3.2.2 on 2021-05-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company_region', models.CharField(blank=True, max_length=10, null=True)),
                ('company_town', models.CharField(blank=True, max_length=10, null=True)),
                ('company_address', models.CharField(blank=True, max_length=60, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('company_ext', models.CharField(blank=True, max_length=20, null=True)),
                ('company_contact_person', models.CharField(blank=True, max_length=30, null=True)),
                ('company_email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_contact_person', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_email', models.CharField(blank=True, max_length=100, null=True)),
                ('uniform_numbers', models.CharField(blank=True, max_length=50, null=True)),
                ('company_url', models.URLField(blank=True, null=True)),
                ('company_info', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MgmtUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('auth', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('public_key', models.CharField(blank=True, max_length=200)),
                ('private_key', models.CharField(blank=True, max_length=200)),
                ('session_expire', models.DateTimeField()),
                ('action', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
