# Generated by Django 3.2.2 on 2021-05-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mgmtuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
