# Generated by Django 3.2.2 on 2021-05-14 13:40

from django.db import migrations, models
import django.db.models.deletion
import mgmt.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0002_auto_20210514_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('types', models.CharField(blank=True, max_length=30, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('selling_price', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(storage=mgmt.utils.storage.ImageStorage(), upload_to='./static/product_images')),
                ('info', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_id', to='mgmt.companyinfo')),
            ],
        ),
    ]
