# Generated by Django 3.2.2 on 2021-05-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0004_alter_productinfo_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='company_id',
            new_name='company',
        ),
    ]
