# Generated by Django 3.2.2 on 2021-05-14 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0005_rename_company_id_productinfo_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_id', to='mgmt.companyinfo'),
        ),
    ]
