# Generated by Django 3.2.2 on 2021-05-14 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0006_alter_productinfo_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
