# Generated by Django 3.2.2 on 2021-05-14 15:07

from django.db import migrations, models
import mgmt.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0008_alter_productinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='image',
            field=models.ImageField(storage=mgmt.utils.storage.ImageStorage(), upload_to='./static/product_images'),
        ),
    ]
