# Generated by Django 3.2.2 on 2021-05-16 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0009_alter_productinfo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProductInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('types', models.CharField(blank=True, max_length=30, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgmt.companyinfo')),
            ],
        ),
    ]
