# Generated by Django 3.2.2 on 2021-05-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0010_companyproductinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproductinfo',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
