# Generated by Django 3.2.2 on 2021-05-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0012_auto_20210517_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='company',
            new_name='company_id',
        ),
    ]
