# Generated by Django 3.2.2 on 2021-05-19 20:07

from django.db import migrations, models
import django.utils.timezone
import mgmt.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0014_rename_company_id_productinfo_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='image2',
            field=models.ImageField(default=django.utils.timezone.now, storage=mgmt.utils.storage.ImageStorage(), upload_to='./static/product_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinfo',
            name='image3',
            field=models.ImageField(default=django.utils.timezone.now, storage=mgmt.utils.storage.ImageStorage(), upload_to='./static/product_images'),
            preserve_default=False,
        ),
    ]
