# Generated by Django 3.2.2 on 2021-05-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0015_auto_20210519_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='company_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
