# Generated by Django 3.2.2 on 2021-05-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0016_companyinfo_company_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='product_in_stock',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
