# Generated by Django 3.2.2 on 2021-05-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0017_productinfo_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproductinfo',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
