# Generated by Django 3.2.2 on 2021-05-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0018_companyproductinfo_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
