# Generated by Django 3.2.2 on 2021-05-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0019_productinfo_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSelling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('types', models.CharField(blank=True, max_length=30, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('selling_price', models.FloatField(blank=True, null=True)),
                ('selling_amount', models.FloatField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('selling_date', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgmt.companyinfo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgmt.productinfo')),
            ],
        ),
    ]
