# Generated by Django 3.2.2 on 2021-05-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0020_productselling'),
    ]

    operations = [
        migrations.AddField(
            model_name='productselling',
            name='selling_sum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
