# Generated by Django 3.2.2 on 2021-05-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0021_productselling_selling_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productselling',
            name='product',
        ),
        migrations.AddField(
            model_name='productselling',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
