# Generated by Django 3.2.2 on 2021-05-25 12:15

from django.db import migrations, models
import mgmt.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0022_auto_20210524_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgmtuser',
            name='image',
            field=models.ImageField(default='', storage=mgmt.utils.storage.ImageStorage(), upload_to='./static/user_images'),
            preserve_default=False,
        ),
    ]
